version: 0.2

env:
  variables:
    AWS_REGION: "us-east-2"
    ECR_REPO: "943708588556.dkr.ecr.us-east-2.amazonaws.com/flow-phenograph"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo "Building Docker image (no flowcore-base)..."
      - docker build -t flow-phenograph:latest .
      - docker tag flow-phenograph:latest $ECR_REPO:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPO:latest
      - echo "Build completed successfully!"
