version: 0.2

env:
  variables:
    AWS_REGION: "us-east-2"
    ECR_REPO: "943708588556.dkr.ecr.us-east-2.amazonaws.com/flow-phenograph"

phases:
  pre_build:
    commands:
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo "===== Step 1: Build flowcore-base image ====="
      - docker build -f Dockerfile.flowcore -t flowcore-base:latest .

      - echo "===== Step 2: Build final phenograph image ====="
      - docker build -f Dockerfile -t flow-phenograph:latest .

      - echo "===== Step 3: Tag final image for ECR ====="
      - docker tag flow-phenograph:latest $ECR_REPO:latest

  post_build:
    commands:
      - echo "Pushing final phenograph image to ECR..."
      - docker push $ECR_REPO:latest

artifacts:
  files:
    - buildspec.yml
