FROM bioconductor/bioconductor_docker:RELEASE_3_17

RUN apt-get update && apt-get install -y \
    libhdf5-dev libgsl-dev libssl-dev libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN R -e "install.packages(c('flowCore','cytolib','RProtoBufLib'), repos='https://cloud.r-project.org/')"
